### ISSUE TITLE
MijnTuin branding logo & icon

### ISSUE THREAD

**Issue by myTselection** [myTselection/MijnTuin#1]
awaiting pull request approval https://github.com/home-assistant/brands/pull/4207

**Comment by myTselection** [comment]
new PR since I used wrong folder name case: https://github.com/home-assistant/brands/pull/4214

**Comment by klaasnicolaas** [comment]
Amall note: you could also have made the adjustments in your first PR 😉

**Comment by myTselection** [comment]
merged

**Comment by myTselection** [comment]
I had renamed my branch case too, which closed the PR. Probably didn't need to do that one :)
