### ISSUE TITLE
Wow!! Really cool, but..

### ISSUE THREAD

**Issue by Bart-van-Gorp** [myTselection/MijnTuin#7]
I love this integration. Although I'd like to have a check mark when a task is done, so it disappears from the to do list for that month. Are you able to adjust the code and add this option?

**Comment by Bart-van-Gorp** [comment]
![Screenshot_20230926-004053](https://github.com/myTselection/MijnTuin/assets/6367588/c2fe3c71-123d-45b6-b268-0de1ef8fd13a)
@

**Comment by myTselection** [comment]
Thx for the feedback. Indeed I believe this would be a good idea. I'll look into it (although may take some time as I'm first finalizing another new integration ;) )

**Comment by Bart-van-Gorp** [comment]
![Screenshot_20231001-122812](https://github.com/myTselection/MijnTuin/assets/6367588/38c46657-1ef6-4fac-9720-72555c8d147a)
I've shared your integration on Facebook, since I think it deserves the attention of everyone that like plants without the proper knowledge to take care of them. This integration is really good. Please maintain it like as suggested.

**Comment by myTselection** [comment]
added in R1.4.0
