### ISSUE TITLE
Overkill of devices

### ISSUE THREAD

**Issue by groenmarsmannetje** [myTselection/MijnTuin#9]
The Home Assistant concept of Devices is misused in this integration. It makes much more sense to setup one MijnTuin Device and put all entities into that single device. Then it is also makes more sense to assign a room (garden) at device level.

**Comment by myTselection** [comment]
Hi, thanks for your feedback and I fully agree.
That was also exactly what I tried to achieve last weekend with the latest release. But it may only become visible in your environment if you'd delete the integration and set it up again. No sensor names should change, only all assembled within 1 device
